apiVersion: apps/v1
kind: Deployment
metadata:
  name: jetlag-core
  labels:
    app: jetlag-core
  namespace: jetlag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jetlag-core
  template:
    metadata:
      labels:
        app: jetlag-core
    spec:
      imagePullSecrets:
        - name: marcindz88-docker-registry
      containers:
        - image: ghcr.io/marcindz88/jetlag/jetlag-core:latest
          imagePullPolicy: Always
          name: jetlag-core
          env:
            - name: GAME_REDIS_HOST
              value: jetlag-redis.jetlag.svc.cluster.local
          ports:
            - containerPort: 9999
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 512Mi
              memory: 512Mi
            requests:
              cpu: 100m
              ephemeral-storage: 256Mi
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: jetlag-core-service
spec:
  type: ClusterIP
  selector:
    app: jetlag-core
  ports:
    - port: 80
      targetPort: 9999

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jetlag-core-service
spec:
  tls:
    - hosts:
        - www.api.jetlag.gg
        - api.jetlag.gg
      secretName: jetlag-cert
  rules:
    - host: www.api.jetlag.gg
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: jetlag-core-service
                port:
                  number: 80
    - host: api.jetlag.gg
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: jetlag-core-service
                port:
                  number: 80
